blank_issues_enabled: false
contact_links:
    - name: Ask a Question
      url: https://github.com/thiagoferolla/chat-adapter-mattermost/discussions
      about: Ask questions and discuss with the community
